### ISSUE TITLE
Speed up match saving in matchmaking

### ISSUE THREAD

**Issue by Fabian-Sommer** [Fabian-Sommer/HeroesLounge#100]
Currently, saving matches is done one by one, causing it to take multiple minutes and scratching php timelimit. Bulk insertion could help speed this up.

**Comment by rogusdev** [comment]
How does "saving matches" work?  Where is the code?

**Comment by rogusdev** [comment]
@Astraeus- said "I believe it refers to the createMatch in Swiss.php"

**Comment by rogusdev** [comment]
I created a wiki placeholder for this, would love more details from @Fabian-Sommer :
https://github.com/Fabian-Sommer/HeroesLounge/wiki/Generating-matches-for-a-Division-in-a-Season-in-a-Region

**Comment by rogusdev** [comment]
I have started working on it, although it looks like @Fabian-Sommer has claimed it as well, I'm mostly curious to investigate and also potentially do some cleanup
