### ISSUE TITLE
Timezone indication for playoff bracket matches

### ISSUE THREAD

**Issue by Astraeus-** [Fabian-Sommer/HeroesLounge#106]
I noticed that for larger timezones the timezone indication on matches can be quite large and mess up our formatting.

![image](https://user-images.githubusercontent.com/6303961/56208190-d3e28a00-6050-11e9-8cb8-63ecd0132003.png)

Perhaps to save time accounting for formatting it's better to just move this to the top of the page in the header?

**Comment by rogusdev** [comment]
That's resolved in one of my open PRs: https://github.com/Fabian-Sommer/HeroesLounge/pull/103/files#r275168803

**Comment by rogusdev** [comment]
Resolved by #103
