### ISSUE TITLE
Double elimination playoff losers bracket spoilers are shown when BYEs are present

### ISSUE THREAD

**Issue by rogusdev** [Fabian-Sommer/HeroesLounge#111]
https://discordapp.com/channels/200267155479068672/230800342579806208/575759772389867521

the hiding spoilers thing isnt quite working right in a double elim bracket:
https://heroeslounge.gg/tournament/nut-cup

You can see the teams seeded into the lower bracket after loosing a game if they're first matched against a bye :NotLikeSloth:

**Comment by Astraeus-** [comment]
Is this still a bug? I checked the Nut Cup and it appears to have been fixed? @rogusdev

**Comment by rogusdev** [comment]
Hmm I must not have tagged it on the PR for it: https://github.com/Fabian-Sommer/HeroesLounge/pull/112
