### ISSUE TITLE
Merge side navigation with top navigation

### ISSUE THREAD

**Issue by Astraeus-** [Fabian-Sommer/HeroesLounge#131]
Recently the create team button was moved out of the navigation. (And instead listed at registration for events / seasons). This has lead to difficulties for users and moderators to create a new team and will cause problems for users wishing to make teams when there aren't any registrations open.

**Comment by Fabian-Sommer** [comment]
I am perfectly fine with users not being able to create a team while they cannot use said team for anything anyway. CreateTeam on its own does not warrant a spot in the navigation. We could put it under a new tab which also includes all of the current sidebar (or at least all the current team stuff that is on the sidebar, and the profile on another tab. That way we can finally get rid of the sidebar)
