### ISSUE TITLE
Linking to user profiles with sloth.id instead of user.id

### ISSUE THREAD

**Issue by Astraeus-** [Fabian-Sommer/HeroesLounge#141]
Currently the Heroes Lounge website uses the underlying `sloth.user.id` as reference to load the correct user profile. https://heroeslounge.gg/user/view/55. However this rarely, if ever, lines up with the `sloth.id` which we output on the api. This makes it near impossible for third party tools to create direct links to user profile pages.

Would we be open to changing this to `sloth.id` for linking to user profiles? Aside from changing the profile loading logic and updating our own references to user profiles it doesn't seem like a lot of work, however a different solution may be more fitting.

**Comment by Fabian-Sommer** [comment]
We can do that
