### ISSUE TITLE
Wrong Heroes Lounge account associated with game

### ISSUE THREAD

**Issue by Astraeus-** [Fabian-Sommer/HeroesLounge#148]
In this [match](https://heroeslounge.gg/match/view/7125) the wrong account was associated with the game. [Grumpypuppy](https://heroeslounge.gg/user/view/1028) is the account that got associated, but it should have been [grumpypuppy_1](https://heroeslounge.gg/user/view/8762).

I believe this is happens when the player is a sub player, but there are multiple accounts registered with a similar battlenet name. The below code is responsible for finding the sub player Heroes Lounge account, but `array_search` returns the first match and thus doesn't take into account that there could be multiple eligible matches.

```PHP
$allKey = array_search(strtolower($playerDetails["m_name"]), $this->allSlothNames);
```

I don't know if there's any additional data to be able to 100% identify a player or that this is the best that we can do.

**Comment by Fabian-Sommer** [comment]
While there is a full battle tag somewhere in the replay it is buried very deep and not supported by the parser, so this is unfortunately the best we can do.
