### ISSUE TITLE
Discord tags can not contain unicode emojis

### ISSUE THREAD

**Issue by Astraeus-** [Fabian-Sommer/HeroesLounge#17]
I got messaged by captain [Lecobra7](https://heroeslounge.gg/user/view/3508) that she didn't have a Discord tag defined on the website.
I tried adding their tag Lecobra🌸#6969 on the backend, but we don't handle emoji's as part of tags properly.

**Comment by Fabian-Sommer** [comment]
Fixed by setting database column to utf8mb4 instead of utf8
