### ISSUE TITLE
Social links: Allow using the Social Links for YouTube channels

### ISSUE THREAD

**Issue by Astraeus-** [Fabian-Sommer/HeroesLounge#195]
From a ticket in the Discord:
> The feature of adding a "YouTube URL" to the Social Links portion of a HeroesLounge team description has been broken by the new "@nickname" feature of YouTube.
For instance, using the URL https://www.youtube.com/@HeroesLoungegg in this field will result in this error.

![image](https://user-images.githubusercontent.com/6303961/219975253-36b26e73-a277-412a-94fa-686709f1ebf0.png)

![image](https://user-images.githubusercontent.com/6303961/219975249-e548640b-f871-4ebc-aced-e84b025de25a.png)

**Comment by Yasir761** [comment]
Can you provide more information on this?

**Comment by Astraeus-** [comment]
> Can you provide more information on this?

Sure, we currently validate that a YouTube link looks like a YouTube link. For this we do some very simple matching against the following regex:

https://github.com/Fabian-Sommer/HeroesLounge/blob/0d61fa03b7a85659fabe1d5fd1b2e32e6694c94e/plugins/rikki/heroeslounge/models/Team.php#L32

The `youtube_url` can be set for teams in a number of different components, for example:
https://github.com/Fabian-Sommer/HeroesLounge/blob/main/plugins/rikki/heroeslounge/components/CreateTeam.php
https://github.com/Fabian-Sommer/HeroesLounge/blob/main/plugins/rikki/heroeslounge/components/ManageTeam.php

I hope this helps set you off in the right direction.

**Comment by eayildiz** [comment]
I think problem is incomplete regex. Most of youtube channels' url's have '@' character after "youtube.com/" but our regex cannot match with it. If we modify our regex and change relevant functions, we can solve it. But I need to figure out editing in github environment first.
