### ISSUE TITLE
Matchmaking: schedule_date and tbp deadlines are too early

### ISSUE THREAD

**Issue by Astraeus-** [Fabian-Sommer/HeroesLounge#197]
https://github.com/Fabian-Sommer/HeroesLounge/blob/aa952011e7e1a4fa383f33df606a60276eca8a0d/plugins/rikki/heroeslounge/classes/matchmaking/Swiss.php#L21-L23

These timestamps are the UTC values, however they appear to be converted and saved as CE(S)T. This means that they're either set at 22:55 or 23:55 of which the former can often be too early a deadline for teams playing late in the evening on the Sunday.

Update this to be consistent throughout the entire year (or just shift it back an hour).

**Comment by CSNWEB** [comment]
So what do we want to do? Just pushing it back an hour or factoring in the timezone? For the teams in NA are they playing in timezone affected countries / states? I think it would be the easiest to settle for a target country per region and then just use that timezone, which would take care of checking for dst / other time shifts.

**Comment by Astraeus-** [comment]
Currently the only two regions we account for are EU and to a much lesser extent NA.

For the EU region, the common timezone we use for sharing time information is Central European time CE(S)T.
For the NA region, the common timezone is Pacific time PDT / PST, depending on dst.

Ideally, we would have the deadline be at 23:55 irrelevant of dst for each region.
