### ISSUE TITLE
heroeslounge.gg and www.heroeslounge.gg are treated differently

### ISSUE THREAD

**Issue by Astraeus-** [Fabian-Sommer/HeroesLounge#2]
When getting a direct link to a user profile e.g: https://www.heroeslounge.gg/user/view/3458

I get the following message: "You must be logged in to view this page. " 
I am already logged in on a different tab. Navigating to different pages from the linked one doesn't cause this to be changed either.

**Comment by Fabian-Sommer** [comment]
The issue is not being detected as logged in when using the link.

**Comment by Astraeus-** [comment]
Showcased below appears to be the actual issue

![image](https://user-images.githubusercontent.com/6303961/43216474-6553566e-903f-11e8-842d-3c7d88ce3d4e.png)

**Comment by gtelljohann** [comment]
@Fabian-Sommer It looks like the auth cookie is set either with or without `www`, but not accessible from the other, so it seems like the easiest way to fix this would be to have non www urls redirect to their www counterparts.  I can look up how - what service do we use to host the site?

**Comment by Astraeus-** [comment]
I know that Siteground is our hosting provider, pretty certain that their web hosting service is built on NGINX

**Comment by Fabian-Sommer** [comment]
I previously tried to reroute all www. to without www., but this broke all links. Maybe the other way around works

**Comment by gtelljohann** [comment]
I'm not sure how to update `.htaccess`, but I think it would be this:
```
    ## Redirect non www urls to www
    RewriteCond %{HTTP_HOST} ^heroeslounge.gg [NC]
    RewriteRule (.*) https://www.heroeslounge.gg/$1 [R,L]
```

**Comment by K-JBoon** [comment]
.htaccess rules would be this

```
<IfModule mod_rewrite.c>
    RewriteEngine On

    RewriteCond %{HTTP_HOST} !heroeslounge.gg
    RewriteCond %{HTTP_HOST} !^(.+)\.(.+)\.(.+)
    RewriteRule ^(.*)$ https://www.%{HTTP_HOST}/$1 [L,R=301]
</IfModule>
```

if you want to do it programatically you'd hook into App::before to modify host header on the request, and then redirect from there (this takes significantly longer)

**Comment by Fabian-Sommer** [comment]
I ended up redirecting www to non-www using a .htaccess rewrite rule
