### ISSUE TITLE
Limit size of images

### ISSUE THREAD

**Issue by Fabian-Sommer** [Fabian-Sommer/HeroesLounge#38]
We use TinyPNG for compression of images, which fails to do so once they are >100MB. Size of all images that can be uploaded (profile and team pics) needs to be limited accordingly.

**Comment by Astraeus-** [comment]
Currently some users have used .svg files for their team logo. We're going to need to be more strict about only supporting the .png file format as tinyPNG only supports png images. (Also OBS struggles with .svg files for our casters too)
