### ISSUE TITLE
Matches today API endpoint

### ISSUE THREAD

**Issue by Astraeus-** [Fabian-Sommer/HeroesLounge#40]
The current [matches today endpoint](https://heroeslounge.gg/api/v1/matches/today) is based on the current date on the server. This means that matches taking place in the US region after 15:00 PT are not included when making a request to the endpoint.
```
public function getTodaysMatches()
    {
        return json_encode(MatchModel::whereDate('wbp','=',date(Carbon::today()))->where('is_played',false)->get());
    }
```

I'm not entirely sure what the best solution would be, but probably along the lines of getting the games from the next day that are in NA before a certain time.

**Comment by rogusdev** [comment]
I'll take a look around.  I assume we need to pass a timezone or UTC time range
