### ISSUE TITLE
Rework time formats for NA users

### ISSUE THREAD

**Issue by Fabian-Sommer** [Fabian-Sommer/HeroesLounge#46]
Times displayed (upcoming matches, schedule matches) should be in AM/PM for sloths with NA as their region. Scheduling should also be in this format for them.

**Comment by gtelljohann** [comment]
@Fabian-Sommer I'll take a stab at this.  Do you want it to be based on the user's region or based on whether the timezone is an America timezone?

**Comment by Fabian-Sommer** [comment]
I think we want to base it on the timezone so that it also works for users that are not logged in (relevant for upcoming matches)

**Comment by rogusdev** [comment]
Unless @gtelljohann beats me to it, I'll dig in on this shortly.

**Comment by gtelljohann** [comment]
go for it, I got distracted and still haven't finished setting up vagrant

**Comment by rogusdev** [comment]
@gtelljohann vagrant setup should be < 15-20 minutes even with vagrant and virtualbox install all the way to heroeslounge running locally so good luck :)

**Comment by rogusdev** [comment]
Should be super easy now, just copy: https://github.com/Fabian-Sommer/HeroesLounge/pull/99/files

Add new method(s) in TiumezoneHelper to determine the time (24hr vs am/pm), date (month before day or vice versa), and datetime (combined) formats to use given a timezone (string starts with "America/" for now?  any others?)

Then calculate the necessary format strings in the various components, then use the format strings in the default.htm views.

I'll get to this later this week if it isn't done before then.
