### ISSUE TITLE
Delete match relations when deleting match

### ISSUE THREAD

**Issue by Fabian-Sommer** [Fabian-Sommer/HeroesLounge#49]
Deleting a match from backend does not cause its relations (rows stored in rikki_heroeslounge_team_match) to be deleted as well. So from a teams point of view, that match looks like it still exists, but it wont be found when accessed.
Probably fixable with a small tweak in the relation definition.

**Comment by Astraeus-** [comment]
Going to have a shot at this. Do you also want the relations between match and caster removed when this happens? (rows stored in rikki_heroeslounge_match_caster)

**Comment by Fabian-Sommer** [comment]
There should be no more references to the object anywhere in the database, so yes.
