### ISSUE TITLE
Teams updating roster during seasons 

### ISSUE THREAD

**Issue by Astraeus-** [Fabian-Sommer/HeroesLounge#53]
Currently it's not possible for any team to update their rosters on the website when there is a season running.

It would be a lot nicer if only rosters of teams participating in an active season or tournament are locked. This would allow people to form and prepare their team if they join heroeslounge during a running season.

**Comment by Astraeus-** [comment]
@Fabian-Sommer This is probably also relevant for division s teams when they're forming.

**Comment by Fabian-Sommer** [comment]
The relevant code in ManageTeam.php:

`
                $this->seasons = Seasons::where('is_active', 1)->where('region_id', $this->team->region_id)->get();
                $id = $this->team->id;
                $lock = $this->seasons->filter(function ($season) use ($id) {
                    if ($season->reg_open == 0) {
                        if ($season->teams()->where('team_id', $id)->count() > 0) {
                            return true;
                        }
                    }
                });
                $this->rosterLocked = $lock->count() > 0 ? true : false;`

should lock rosters only for teams that are participating in an active season, but not for new teams.
Are you sure this issue exists?

**Comment by Astraeus-** [comment]
The issue came up on the 5th of January in support desk and has this has been the case for as long as I can remember.
