### ISSUE TITLE
Add spoiler filter

### ISSUE THREAD

**Issue by Fabian-Sommer** [Fabian-Sommer/HeroesLounge#62]
Some users want to see playoff brackets and schedules without seeing results, especially for Div S. We could provide a switch similar to how HGC did it.

**Comment by rogusdev** [comment]
Would the switch be universal for the user?  Or per division/season/region, anything like that?  What about just a local cookie vs saved in user account across browser sessions?

**Comment by Fabian-Sommer** [comment]
Ideally, it would be consistent for each user across everything, keeping in mind that the user may not have an account on our site. Toggling still needs to be easily accessible from each relevant page.

**Comment by rogusdev** [comment]
So I'm seeing a pages for this:
http://localhost:8080/hl/na-season-1/division-5  # division standings, plus recent results on the right
== plugins\rikki\loungeviews\components\divisionoverview\default.htm
http://localhost:8080/hl/season-7/playoff/Cup  # playoff brackets are same as tournaments, right?
http://localhost:8080/hl/tournament/eu-division-s-qualifiers-1  # tournament is different from playoff?...
== plugins\rikki\loungeviews\components\playoffoverview\default.htm
http://localhost:8080/hl/team/view/NEWT  # right column on a team has standings plus recent results (same as division standings)
== ??
--- localhost:8080/hl/match/view/4429  # individual match already has a "toggle statistics" button hiding results -- do we want to tie that default open/close state to the new spoilers on/off state?
--- http://localhost:8080/hl/user/view/4246  # individual players already have "toggle maps/heroes" and don't show specific games anyway

Are there any other pages that should be affected by this?
