### ISSUE TITLE
Enhance API

### ISSUE THREAD

**Issue by Fabian-Sommer** [Fabian-Sommer/HeroesLounge#64]
Requested endpoints:

- Division recent results: /division/{id}/recentresults => returns an array containing recent results (last day?). Entries need team names, logos and the score

- Division standings: /division/{id}/standings => returns an array containing the standings table. Entries need position, team name, team logo, wins, losses, map wins.

- Division standings team: /division/{division}/standings/{team} => returns the standings info. Entry needs position, team name, team logo, wins, losses, map wins.

- Division hero statistics: /division/{id}/herostats => returns an array containing hero participation statistics. Entries need number of picks, number of bans, number of wins.

- Role data: /roles/{id} => returns the role name (tank, bruiser, etc)

- Sloth hero data: /sloth/{id}/herostats => returns an array containing heroes played statistics. Entries need hero name, times played, wins.

Most of the data is already being calculated somewhere (except sloth hero data), but especially for stats and recent results this only happens in the component that renders the data. This needs to be refactored to happen in the model, so both component and API can access it.

**Comment by rogusdev** [comment]
Ha. Free for all then?  Or any particular ways desired for enhancement?  Even just a link to a chat in discord to give context could spruce this one up to be more easily actionable.

**Comment by Fabian-Sommer** [comment]
I edited the original post with more concrete requests
