### ISSUE TITLE
Refactor how we use the users timezone

### ISSUE THREAD

**Issue by Fabian-Sommer** [Fabian-Sommer/HeroesLounge#65]
Currently, we do AJAX calls on every page that displays time to account for the users timezone. This induces high server load. It would be great if we could save the timezone across a session and use it directly.

**Comment by rogusdev** [comment]
Can we just use UTC serverside for everything have have the client side browser convert to local time there?  That is what is typical in my experienece.

**Comment by Fabian-Sommer** [comment]
For legacy reasons, our server uses Berlin time for everything (we can change that of course). The important part here is to do the conversion on client side

**Comment by rogusdev** [comment]
I see 3 related commits:

User timezone in js:
https://github.com/Fabian-Sommer/HeroesLounge/commit/52fbc4afbf18d3a4515b3dddd8bc301fd4aa0741

Default timezone:
https://github.com/Fabian-Sommer/HeroesLounge/commit/6a859d8f786c23caa67117f785d07c08d6ad3bf8

Timezone conversions:
https://github.com/Fabian-Sommer/HeroesLounge/commit/aed5ad0c3cdcaa6028f84a9028ef5843ecf034e6

Are there any others I should look at?


Clearly timezone is used on scheduling a match which I see in the backend:
http://localhost:8080/hl/backend/rikki/heroeslounge/match/create
And:
http://localhost:8080/hl/backend/rikki/heroeslounge/match/update/107
And certainly displayed on the frontend calendar:
http://localhost:8080/hl/calendar

Is there anywhere for users to schedule matches on the frontend?
http://localhost:8080/hl/team/match/ChrisTest
Or:
http://localhost:8080/hl/team/view/ChrisTest
^ I can’t see any matches here, and I’m not sure what I need to do to set these up

Basically I want to know where all the different places I should be testing are, and how to test them.


Can someone point me in a good direction for configuring a local db to have the necessary conditions to have 2 teams with players in a division in a season with a scheduled match?  I'll gladly run SQL.  So far I've come across these tables:

```
SELECT * FROM rikki_heroeslounge_team_apps ORDER BY id DESC LIMIT 2;
SELECT * FROM rikki_heroeslounge_match ORDER BY id DESC LIMIT 2;
SELECT * FROM rikki_heroeslounge_team_match ORDER BY id DESC LIMIT 2;
```

I've got stuff to show up on the public calendar, but it doesn't show up on my team view page.


I also notice that local config is in UTC by default:
`grep 'timezone' /opt/lampp/htdocs/hl/config/app.php`
which might affect my testing.  What is this config in prod?  Is it 'Europe/Berlin'?  Once you confirm what it is in prod, I will make it set by the local install scripts so everyone will be consistent.

**Comment by rogusdev** [comment]
So, just starting with the public facing calendar:
themes\HeroesLounge-Theme\pages\calendar.htm

This loads component UpcomingMatches:
plugins\rikki\heroeslounge\components\UpcomingMatches.php

Which in turn loads its default page:
plugins\rikki\heroeslounge\components\upcomingmatches\default.htm

Which itself calls a bunch of AJAX to the backend to render a partial with the actual calendar of matches:
plugins\rikki\heroeslounge\components\upcomingmatches\calendar.htm

In theory using the user's timezone -- although this does not work in my local testing.

2 questions:
1) How does jQuery.request work such that it actually updates the page?  The 2 pages of October docs on partials and request that I could find, neither suggests this behavior:
https://octobercms.com/docs/ajax/update-partials
https://octobercms.com/docs/ajax/javascript-api
Although there are some vague hints at it here:
https://octobercms.com/docs/plugin/components#render-partial-method
https://octobercms.com/docs/ajax/handlers
courtesy of:
https://stackoverflow.com/questions/42326511/rendering-a-component-partial-from-code-in-octobercms
Are there any better docs you can point me at?  The source code for October CMS's implementation of request seems to make some sense of this, but I'd love a human explanation:
https://github.com/octobercms/october/blob/master/modules/system/assets/js/framework.js
2) Is there a session object somewhere of the currently logged in user that we can add data to?  I see SideNav gets the user and the sloth:
plugins\rikki\loungeviews\components\SideNav.php
But I can't find anything that seems to do anything with a session.
I could get the timezone off the sloth model and use that, but I can't find where that actually gets set, not even on the frontend as a user, so I'm not sure how up to date I trust it to be.  If we could update that every time the user logged in, that might be good enough, baring people on airplanes on their laptop or phone (traveling across timezones in a single session).  Where does timezone get set on sloths?  (still also interested in the initial question of session data tracking)

**Comment by rogusdev** [comment]
Oh an I'm also curious how to access the "accepted casts" and "denied casts" lists on the calendar that I see in the code -- I'm not sure what those are or where they come from.  If they are dead code, that would certainly simplify some of the effort to get all this cleaned up.

**Comment by rogusdev** [comment]
OK, I found the October CMS Session functionality:
https://octobercms.com/docs/services/session

It appears we currently only use this in a plugin:
plugins\rikki\heroeslounge\Plugin.php

But it looks simple enough to add timezone to the session like so:
1) on any page load, check if the current session has a timezone
2) if no timezone exists on the session, if the user is logged in, use the sloth's timezone
3) if there is still no session timezone, add the javascrip0t to make an ajax call on document ready to get user's browser timezone and send it back to the backend, where we then store that timezone on the session and on the sloth
4) when a user logs in, if they have no timezone on their sloth, add it from the session

I believe that should cover everything without repeated ajax calls, and avoids adding any new UI elements for timezone management., although I might still add a display of the current timezone somewhere in the user profile for the logged in user.

This does suggest merging a whole bunch of functionality back together in the calendar and possibly other places that are setup as partials that no longer need to / should be (to avoid unnecessary ajax) but I might do that as a separate PR, we shall see.

Does that all sound good/accurate?

**Comment by Fabian-Sommer** [comment]
> 2 questions:
> 
> 1. How does jQuery.request work such that it actually updates the page?  The 2 pages of October docs on partials and request that I could find, neither suggests this behavior:
>    https://octobercms.com/docs/ajax/update-partials
>    https://octobercms.com/docs/ajax/javascript-api
>    Although there are some vague hints at it here:
>    https://octobercms.com/docs/plugin/components#render-partial-method
>    https://octobercms.com/docs/ajax/handlers
>    courtesy of:
>    https://stackoverflow.com/questions/42326511/rendering-a-component-partial-from-code-in-octobercms
>    Are there any better docs you can point me at?  The source code for October CMS's implementation of request seems to make some sense of this, but I'd love a human explanation:
>    https://github.com/octobercms/october/blob/master/modules/system/assets/js/framework.js

For some instances https://laravel.com/docs/5.8 might be helpful as October is built on Laravel. I do not know a really good doc for October itself.

> 2. Is there a session object somewhere of the currently logged in user that we can add data to?  I see SideNav gets the user and the sloth:
>    plugins\rikki\loungeviews\components\SideNav.php
>    But I can't find anything that seems to do anything with a session.
>    I could get the timezone off the sloth model and use that, but I can't find where that actually gets set, not even on the frontend as a user, so I'm not sure how up to date I trust it to be.  If we could update that every time the user logged in, that might be good enough, baring people on airplanes on their laptop or phone (traveling across timezones in a single session).  Where does timezone get set on sloths?  (still also interested in the initial question of session data tracking)
>    EDIT: ok I see where the timezone gets set on the `onTimezoneDetection` call on the various layouts (is there any way to have one shared functionality for this instead of copy-pasting?).  The "fun" part about this one is that the ajax call is made on every single page load, but the timezone only ever gets updated the very first time!  So probably just not doing that would be a nice step forward -- set timezone on signup or login or something and then give a UI element somewhere for users to change their timezone.  And then rather than doing ajax calls with timezone to get the calendar, instead just use current user's timezone.
>    ^ Would that suffice to resolve this issue?

This sounds great if you can make it work.




> OK, I found the October CMS Session functionality:
> https://octobercms.com/docs/services/session
> 
> It appears we currently only use this in a plugin:
> plugins\rikki\heroeslounge\Plugin.php
> 
> But it looks simple enough to add timezone to the session like so:
> 
> 1. on any page load, check if the current session has a timezone
> 2. if no timezone exists on the session, if the user is logged in, use the sloth's timezone
> 3. if there is still no session timezone, add the javascrip0t to make an ajax call on document ready to get user's browser timezone and send it back to the backend, where we then store that timezone on the session and on the sloth
> 4. when a user logs in, if they have no timezone on their sloth, add it from the session
> 
> I believe that should cover everything without repeated ajax calls, and avoids adding any new UI elements for timezone management., although I might still add a display of the current timezone somewhere in the user profile for the logged in user.
> 
> This does suggest merging a whole bunch of functionality back together in the calendar and possibly other places that are setup as partials that no longer need to / should be (to avoid unnecessary ajax) but I might do that as a separate PR, we shall see.
> 
> Does that all sound good/accurate?

Sounds mostly good. I would not use the sloths timezone at the start of a session as it may be out of date, but rather rely on a single js call. The one saved in sloth can be used as a fallback option.

We would have to investigate how long sessions persist, with this approach they should not last longer than 24h (or otherwise, we can save when the timezone was last updated and update it when this was more than one day ago).

**Comment by rogusdev** [comment]
> I also notice that local config is in UTC by default:
grep 'timezone' /opt/lampp/htdocs/hl/config/app.php
which might affect my testing. What is this config in prod? Is it 'Europe/Berlin'? Once you confirm what it is in prod, I will make it set by the local install scripts so everyone will be consistent.

I'm still curious about this because the default timezone on the server definitely matters for converting the times from the db properly

Past that, my PR does not use sloth timezone for anything, and just puts timezone on the session every time a session does not already have a timezone

**Comment by Fabian-Sommer** [comment]
The timezone on the server is UTC from now on

**Comment by rogusdev** [comment]
> The timezone on the server is UTC from now on

Specificity how is that set?  In config/app?  In linux?  Both/neither?  What about the mysql db default timezone?

**Comment by Fabian-Sommer** [comment]
The setting in config/app is set to UTC and as far as I know is the only relevant entry for this
