### ISSUE TITLE
Add nice overview page for Division S

### ISSUE THREAD

**Issue by Fabian-Sommer** [Fabian-Sommer/HeroesLounge#66]
Once Div S is running, we want a page showing standings, schedules, etc.
We might just reuse what we have for divisions, but maybe we can do better

**Comment by rogusdev** [comment]
What would be different from the curre t page? https://heroeslounge.gg/eu-division-s-season-1/eu-division-s-season-1

**Comment by Fabian-Sommer** [comment]
I think the current page does it for now (we did just reuse what we had for divisions), however in the future this may be relevant again (when there are playoffs for example, multiple phases, .... Some page that reflects the structure of this might be nice). Right now there is some overlap with https://heroeslounge.gg/divisionS/schedule which is a manually maintained static page, we could merge these together.

This issue does include a bit of figuring out what such a page needs and how it should look like
