### ISSUE TITLE
Make Division S standings prettier

### ISSUE THREAD

**Issue by Fabian-Sommer** [Fabian-Sommer/HeroesLounge#70]
Currently, we show two headlines for the standings of Division S, which are both almost equal. The second headline should read something that is different from the division title. Instead, we want a new attribute for divisions that defines what is shown in that place.

**Comment by rogusdev** [comment]
Looks like you mean:
https://heroeslounge.gg/eu-division-s-season-1/eu-division-s-season-1
and 
https://heroeslounge.gg/na-division-s-season-1/na-division-s-season-1
Is that correct?

**Comment by Fabian-Sommer** [comment]
Indeed, these are the only pages online right now. I would expect that there may be more like them in the future.
The main problem why we would not want to change the title is that the calendar shows scheduled matches alongside the title of the division, which is not equal to what should be on the two pages linked above. The title is also used to identify the division in the backend (which is already a bit messy since we have several divisions titled 'Division 1' and so on, but that is a separate issue).
Another thing that could be improved upon are the URLs, but that can be handled by the slug which already exists.

**Comment by rogusdev** [comment]
I see this is the page in the repo;
plugins\rikki\loungeviews\components\divisionoverview\default.htm

And therefore the fields that are questionable are these:
```
<h1>{{__SELF__.div.season.title}}</h1>
<h2>{{__SELF__.div.title}}</h2>
```

I'm not sure exactly what is desired to change specifically.  Where are those 2 fields used elsewhere?  Why can't we just change `div.title` to whatever we want to show as the subheading?

**Comment by rogusdev** [comment]
Ah, if I experiment, I can see this one: http://localhost:8080/hl/na-season-1/division-5 -- live site: https://heroeslounge.gg/na-season-1/division-5

which is from:
```
MariaDB [hl]> SELECT * FROM rikki_heroeslounge_seasons WHERE id = 5;
+----+--------------+--------------+-------------+---------------+-----------+---------------------+---------------------+------------+----------+-----------+-----------+------+
| id | title        | round_length | slug        | current_round | is_active | created_at          | updated_at          | deleted_at | reg_open | mm_active | region_id | type |
+----+--------------+--------------+-------------+---------------+-----------+---------------------+---------------------+------------+----------+-----------+-----------+------+
|  5 | [NA]Season 1 |            8 | na-season-1 |             8 |         1 | 2018-09-26 19:22:22 | 2019-01-14 10:00:05 | NULL       |        0 |         0 |         2 |    1 |
+----+--------------+--------------+-------------+---------------+-----------+---------------------+---------------------+------------+----------+-----------+-----------+------+
1 row in set (0.00 sec)

MariaDB [hl]> SELECT * FROM rikki_heroeslounge_divisions WHERE id = 75;
+----+-----------+---------------------+---------------------+------------+------------+------------+------------+
| id | season_id | created_at          | updated_at          | deleted_at | title      | slug       | playoff_id |
+----+-----------+---------------------+---------------------+------------+------------+------------+------------+
| 75 |         5 | 2018-10-30 21:58:02 | 2018-10-30 21:58:32 | NULL       | Division 5 | division-5 |       NULL |
+----+-----------+---------------------+---------------------+------------+------------+------------+------------+
```

Which seems to come from:
http://localhost:8080/hl/backend/rikki/heroeslounge/season/update/5 (season title)
and:
http://localhost:8080/hl/backend/rikki/heroeslounge/division/update/75 (division title)

This in turn leads me to:
plugins\rikki\heroeslounge\models\season\fields.yaml
and:
plugins\rikki\heroeslounge\models\division\fields.yaml

(I also see that these can be edited in the admin from: http://localhost:8080/hl/backend/indikator/devtools/editor --after clicking down to the matching dir path)

What are the columns.yaml files for in those same folders?  They appear to be subsets of fields -- did the yaml config file/format change and we not remove the old files?

I see that this is related to the "rikki" plugin which has a changelog of sorts here:
http://localhost:8080/hl/backend/system/updates/details/rikki-heroeslounge/changelog

which does indicate db table changes however I am unclear on the migration process -- how do you actually update the db to deploy changes to the schema?

I added a new field to the season yaml:
```
    other:
        label: Other
        span: auto
        required: 0
        type: text
```
And it shows up immediately in the admin UI however I had to manually add the db column like so:
```
ALTER TABLE rikki_heroeslounge_seasons ADD COLUMN other VARCHAR(255);
```

And then it saved when I updated in the admin and also shows in the page when I add it there:
```
<h3>{{__SELF__.div.season.other}}</h3>
```

Is that all that is required here?

**Comment by rogusdev** [comment]
This change ^ did not increment the rikki changelog version, looks like that is a manual addition here:
plugins\rikki\heroeslounge\updates\version.yaml

Is that correct?

**Comment by rogusdev** [comment]
Ah actually I see where migrations are now, from this commit modifying this version file:
https://github.com/Fabian-Sommer/HeroesLounge/commit/fedd71859344a30ac061a989f4c1393152e7b012#diff-3801f562f9e0c1b45af5f81e6225eb9b

**Comment by rogusdev** [comment]
Ohhhhh the migrations come from using the builder at:
http://localhost:8080/hl/backend/rainlab/builder

and selecting "heroeslounge" plugin then "database" then "rikki_heroeslounge_divisions" then "Add column" -- define the new column then hit save, and it automatically creates the migration and changelog for you.

Still have to add the new field to fields.yaml it seems.

It seems that the migrations run automatically after adding in builder, and I see documentation here claims that as well:
https://octobercms.com/plugin/rainlab-builder

I'm mildly curious how you handle the deploy process in prod to get the migrations run before the changes are live, or if you normally do separate PRs for adding migrations then adding code relying on the new fields.

**Comment by rogusdev** [comment]
How will people run the new migration after they `git pull`?

**Comment by Astraeus-** [comment]
They can go into their local back-end to Builder, select the updated plugin (E.g: heroeslounge), select versions and then select the version to update to.

**Comment by Fabian-Sommer** [comment]
- The fields.yaml influences which attributes can be set from the backend when creating/modifying records. The columns.yaml decides which attributes are visible when seeing all records from the backend. Neither of them influences which columns are actually in the DB, we use the Builder plugin for that. All columns in the DB are always accessible from the model, so any column that is neither in the fields.yaml nor in the columns.yaml is still fully functional, it just will not be accessible from the backend.

> So what is the new field supposed to represent so I know what to name it? And this lives on the division and not on the season? Why?

For now, the field should hold the name that is displayed exactly at the one location we are talking about, so it could be something like overview_display_title. It should be on Division because for DivS we might have multiple divisions titled 'Standings Phase 1' and 'Standings Phase 2' while still being part of the same season.



> How will people run the new migration after they `git pull`?

Like Astraeus said, Builder can also run migrations (thats also how I deploy on production, so they can be part of the same PR). Alternatively, I think migrations run on their own after some time, not entirely sure.

> All of these connections would likely be relatively easy to document in the github wiki or something to help others jump in even more quickly.

Most of the interplay between themes, pages, components, controllers and so on should be documented on the October Documentation (https://octobercms.com/docs/cms/themes). I will add this link to the front page of this repo.

**Comment by Fabian-Sommer** [comment]
Another thing about our project structure:
Technically, we have 3 plugins called 'Heroeslounge', 'LoungeViews' and 'LoungeStatistics'. LoungeViews and LoungeStatistics just contain more components for the most part (LoungeStatistics everything related to stats, LoungeViews all components that do not render any forms or need to process user input, Heroeslounge for everything else, including models, migrations, API, backend, components that process user input).
