### ISSUE TITLE
Matches endpoint errors when requesting by specifc match id

### ISSUE THREAD

**Issue by Astraeus-** [Fabian-Sommer/HeroesLounge#95]
The matches endpoint for a specific match is currently broken.
E.g: `https://heroeslounge.gg/api/v1/matches/3122` => `http://localhost:8080/hl/api/v1/matches/312`

I expect to get information for the specified match, but instead instead get an error. I assume this an unforeseen side-effect from the update to the `matches/today` endpoint by @rogusdev

**Comment by rogusdev** [comment]
Oh crap, yep, I did not notice that
